export const skillCategories = [
  {
    title: "Programming Languages & Frameworks",
    skills: [
      { name: "Java", level: 95 },
      { name: "JavaScript", level: 95 },
      { name: "TypeScript", level: 95 },
      { name: "Python", level: 90 },
      { name: "PHP", level: 90 },
      { name: "C", level: 80 },
      { name: "C++", level: 75 },
      { name: "C#", level: 80 },
      { name: "Pascal", level: 75 },
      { name: "TCL", level: 80 },
      { name: "VHDL", level: 80 },
    ],
  },
  {
    title: "Front-end Technologies",
    skills: [
      { name: "Angular", level: 95 },
      { name: "React/Next.js", level: 90 },
      { name: "Redux", level: 95 },
      { name: "Prime NG", level: 95 },
      { name: "Tailwind CSS", level: 95 },
      { name: "SASS/SCSS", level: 95 },
      { name: "Bootstrap", level: 90 },
      { name: "Material UI", level: 90 },
      { name: "JQuery", level: 80 },
      { name: "JQuery UI", level: 80 },
    ],
  },
  {
    title: "Backend & Database",
    skills: [
      { name: "Rest API", level: 95 },
      { name: "Microservices", level: 95 },
      { name: "Spring Boot", level: 95 },
      { name: "PostgreSQL", level: 95 },
      { name: "MySQL", level: 95 },
      { name: "Oracle", level: 90 },
      { name: "MongoDB", level: 95 },
      { name: "Redis", level: 90 },
      { name: "Elasticsearch", level: 90 },
      { name: "GraphQL", level: 90 },
    ],
  },
  {
    title: "Cloud & DevOps",
    skills: [
      { name: "AWS", level: 95 },
      { name: "Docker", level: 90 },
      { name: "Kubernetes", level: 90 },
      { name: "GitHub Actions", level: 90 },
      { name: "CI/CD", level: 80 },
    ],
  },
  {
    title: "System Design & soft skills",
    skills: [
      { name: "System Design", level: 95 },
      { name: "Microservice Design", level: 95 },
      { name: "Real-time System Design", level: 90 },
      { name: "Team leadership", level: 90 },
      { name: "Technical mentoring", level: 95 },
      { name: "Communication", level: 95 },
    ],
  },
  {
    title: "Mobile & Other",
    skills: [
      { name: "Ionic", level: 90 },
      { name: "System Design", level: 95 },
      { name: "Agile/Scrum", level: 85 },
      { name: "Team leadership", level: 90 },
      { name: "Technical mentoring", level: 90 },
    ],
  },
];